//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_College
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public int Id { get; set; }

        [Required (ErrorMessage ="Enter Your Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Enter Your Date of Birth")]
        public System.DateTime DOB { get; set; }
        
        [Required(ErrorMessage = "Select Gender")]
        public string Gender { get; set; }
        
        [Required(ErrorMessage = "Enter Your Mobile Number")]
        public string MobileNumber { get; set; }
        
        [Required(ErrorMessage = "Enter Your Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        
        [Required(ErrorMessage = "Enter Your Higher Secondary Percentage")]
        [Display(Name = "HSC Percentage" )]
        public int HSC_Percentage { get; set; }

        [Required(ErrorMessage = "Select Your Department")]
        public int DeptId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
